import { StyleSheet } from "react-native";
import { colors, radius, shadow, spacing, type } from "../theme";

export const styles = StyleSheet.create({
  page: {
    flexGrow: 1,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.md,
    paddingBottom: 130,
  },
  top: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    marginTop: 4,
    marginBottom: spacing.lg,
  },
  eyebrow: type.eyebrow,
  titleSmall: { ...type.subtitle, marginTop: 3 },
  title: { ...type.display, marginTop: 6 },
  section: { ...type.subtitle, marginTop: spacing.xxl, marginBottom: spacing.sm },
  muted: type.caption,
  body: type.body,
  input: {
    minHeight: 54,
    borderRadius: radius.md,
    paddingHorizontal: 16,
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.soft,
  },
  hero: {
    borderRadius: radius.xl,
    padding: spacing.xl,
    marginTop: spacing.lg,
    overflow: "hidden",
    ...shadow.card,
  },
  heroKicker: { fontSize: 10, fontWeight: "800", letterSpacing: 1.4, color: colors.onPrimarySoft },
  heroTitle: { color: "#fff", fontSize: 23, lineHeight: 30, fontWeight: "800", letterSpacing: -0.5, marginTop: 10 },
  heroText: { color: colors.onPrimarySoft, fontSize: 12.5, lineHeight: 18, marginTop: 10 },
  grid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 14, marginTop: spacing.sm },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    marginTop: spacing.md,
    ...shadow.soft,
  },
  productImage: {
    height: 300,
    borderRadius: radius.xl,
    overflow: "hidden",
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  productName: type.label,
  productPrice: { fontSize: 20, fontWeight: "800", letterSpacing: -0.4, color: colors.text, marginTop: 8 },
  stickyBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl,
    backgroundColor: "rgba(250,248,245,0.96)",
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
});
