/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMobileRouteImport } from './routes/admin.mobile'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminFunnelsRouteImport } from './routes/admin.funnels'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCohortsRouteImport } from './routes/admin.cohorts'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminPromotionNewRouteImport } from './routes/admin.promotion.new'
import { Route as AdminProductNewRouteImport } from './routes/admin.product.new'
import { Route as AdminProductIdRouteImport } from './routes/admin.product.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminNotificationNewRouteImport } from './routes/admin.notification.new'
import { Route as AdminCustomerIdRouteImport } from './routes/admin.customer.$id'
import { Route as AdminBannerNewRouteImport } from './routes/admin.banner.new'
import { Route as AdminAiAgentNewRouteImport } from './routes/admin.ai-agent.new'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMobileRoute = AdminMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFunnelsRoute = AdminFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCohortsRoute = AdminCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionNewRoute = AdminPromotionNewRouteImport.update({
  id: '/promotion/new',
  path: '/promotion/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductNewRoute = AdminProductNewRouteImport.update({
  id: '/product/new',
  path: '/product/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductIdRoute = AdminProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminNotificationNewRoute = AdminNotificationNewRouteImport.update({
  id: '/notification/new',
  path: '/notification/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerIdRoute = AdminCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannerNewRoute = AdminBannerNewRouteImport.update({
  id: '/banner/new',
  path: '/banner/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAgentNewRoute = AdminAiAgentNewRouteImport.update({
  id: '/ai-agent/new',
  path: '/ai-agent/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tracking': typeof TrackingRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/funnels': typeof AdminFunnelsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/mobile': typeof AdminMobileRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ai-agent/new': typeof AdminAiAgentNewRoute
  '/admin/banner/new': typeof AdminBannerNewRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/admin/notification/new': typeof AdminNotificationNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/product/new': typeof AdminProductNewRoute
  '/admin/promotion/new': typeof AdminPromotionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tracking': typeof TrackingRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/funnels': typeof AdminFunnelsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/mobile': typeof AdminMobileRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/ai-agent/new': typeof AdminAiAgentNewRoute
  '/admin/banner/new': typeof AdminBannerNewRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/admin/notification/new': typeof AdminNotificationNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/product/new': typeof AdminProductNewRoute
  '/admin/promotion/new': typeof AdminPromotionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tracking': typeof TrackingRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/funnels': typeof AdminFunnelsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/mobile': typeof AdminMobileRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ai-agent/new': typeof AdminAiAgentNewRoute
  '/admin/banner/new': typeof AdminBannerNewRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/admin/notification/new': typeof AdminNotificationNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/product/new': typeof AdminProductNewRoute
  '/admin/promotion/new': typeof AdminPromotionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/profile'
    | '/search'
    | '/tracking'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/cohorts'
    | '/admin/customers'
    | '/admin/funnels'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/mobile'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/team'
    | '/product/$id'
    | '/admin/'
    | '/admin/ai-agent/new'
    | '/admin/banner/new'
    | '/admin/customer/$id'
    | '/admin/notification/new'
    | '/admin/orders/$id'
    | '/admin/product/$id'
    | '/admin/product/new'
    | '/admin/promotion/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/profile'
    | '/search'
    | '/tracking'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/cohorts'
    | '/admin/customers'
    | '/admin/funnels'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/mobile'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/team'
    | '/product/$id'
    | '/admin'
    | '/admin/ai-agent/new'
    | '/admin/banner/new'
    | '/admin/customer/$id'
    | '/admin/notification/new'
    | '/admin/orders/$id'
    | '/admin/product/$id'
    | '/admin/product/new'
    | '/admin/promotion/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/profile'
    | '/search'
    | '/tracking'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/cohorts'
    | '/admin/customers'
    | '/admin/funnels'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/mobile'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/team'
    | '/product/$id'
    | '/admin/'
    | '/admin/ai-agent/new'
    | '/admin/banner/new'
    | '/admin/customer/$id'
    | '/admin/notification/new'
    | '/admin/orders/$id'
    | '/admin/product/$id'
    | '/admin/product/new'
    | '/admin/promotion/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  TrackingRoute: typeof TrackingRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mobile': {
      id: '/admin/mobile'
      path: '/mobile'
      fullPath: '/admin/mobile'
      preLoaderRoute: typeof AdminMobileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/funnels': {
      id: '/admin/funnels'
      path: '/funnels'
      fullPath: '/admin/funnels'
      preLoaderRoute: typeof AdminFunnelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cohorts': {
      id: '/admin/cohorts'
      path: '/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AdminCohortsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotion/new': {
      id: '/admin/promotion/new'
      path: '/promotion/new'
      fullPath: '/admin/promotion/new'
      preLoaderRoute: typeof AdminPromotionNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product/new': {
      id: '/admin/product/new'
      path: '/product/new'
      fullPath: '/admin/product/new'
      preLoaderRoute: typeof AdminProductNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product/$id': {
      id: '/admin/product/$id'
      path: '/product/$id'
      fullPath: '/admin/product/$id'
      preLoaderRoute: typeof AdminProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/notification/new': {
      id: '/admin/notification/new'
      path: '/notification/new'
      fullPath: '/admin/notification/new'
      preLoaderRoute: typeof AdminNotificationNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer/$id': {
      id: '/admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/admin/customer/$id'
      preLoaderRoute: typeof AdminCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banner/new': {
      id: '/admin/banner/new'
      path: '/banner/new'
      fullPath: '/admin/banner/new'
      preLoaderRoute: typeof AdminBannerNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-agent/new': {
      id: '/admin/ai-agent/new'
      path: '/ai-agent/new'
      fullPath: '/admin/ai-agent/new'
      preLoaderRoute: typeof AdminAiAgentNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCohortsRoute: typeof AdminCohortsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFunnelsRoute: typeof AdminFunnelsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMobileRoute: typeof AdminMobileRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAiAgentNewRoute: typeof AdminAiAgentNewRoute
  AdminBannerNewRoute: typeof AdminBannerNewRoute
  AdminCustomerIdRoute: typeof AdminCustomerIdRoute
  AdminNotificationNewRoute: typeof AdminNotificationNewRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
  AdminProductNewRoute: typeof AdminProductNewRoute
  AdminPromotionNewRoute: typeof AdminPromotionNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCohortsRoute: AdminCohortsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFunnelsRoute: AdminFunnelsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMobileRoute: AdminMobileRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAiAgentNewRoute: AdminAiAgentNewRoute,
  AdminBannerNewRoute: AdminBannerNewRoute,
  AdminCustomerIdRoute: AdminCustomerIdRoute,
  AdminNotificationNewRoute: AdminNotificationNewRoute,
  AdminProductIdRoute: AdminProductIdRoute,
  AdminProductNewRoute: AdminProductNewRoute,
  AdminPromotionNewRoute: AdminPromotionNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  TrackingRoute: TrackingRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
